rumbl/lib/rumbl_web/router.ex
defmodule RumblWeb.Router do
  use RumblWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", RumblWeb do
    pipe_through :browser
    get "/users", UserController, :index
    get "/users/:id", UserController, :show
    

    get "/", PageController, :index
  end

  # Other scopes may use custom stacks.
  # scope "/api", RumblWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: RumblWeb.Telemetry
    end
  end
end

rumbl/lib/rumbl/accounts.ex
defmodule Rumbl.Accounts do
    @moduledoc """
      The Accounts context.
      """
    
    alias Rumbl.Accounts.User

    def list_users do
        [
            %User{id: "1", name: "Jose", username: "josevalim"},
            %User{id: "2", name: "Beuce", username: "redrapids"},
            %User{id: "3", name: "Cris", username: "crismccord"}
        ]
    end

    def get_user(id) do
        Enum.find(list_users(),fn map ->
             map.id == id 
            end)
    end

    def get_user_by(params)do
        Enum.find(list_users(),fn map -> 
            Enum.all?(params, fn{key,val} -> 
            Map.get(map, key) == val 
        end)
        end)
    end

end

rumbl/lib/rumbl/accounts/user.change1.ex
defmodule Rumbl.Accounts.User do
    use Ecto.Schema
    import Ecto.Changeset
    
    schema "users" do
        field :name, :string
        field :username, :string

        timestamps()
    end
end

rumbl/lib/rumbl/application.ex
defmodule Rumbl.Application do
  # See https://hexdocs.pm/elixir/Application.html
  # for more information on OTP Applications
  @moduledoc false

  use Application

  def start(_type, _args) do
    children = [
      # Start the Ecto repository
      Rumbl.Repo,
      # Start the Telemetry supervisor
      RumblWeb.Telemetry,
      # Start the PubSub system
      {Phoenix.PubSub, name: Rumbl.PubSub},
      # Start the Endpoint (http/https)
      RumblWeb.Endpoint
      # Start a worker by calling: Rumbl.Worker.start_link(arg)
      # {Rumbl.Worker, arg}
    ]

    # See https://hexdocs.pm/elixir/Supervisor.html
    # for other strategies and supported options
    opts = [strategy: :one_for_one, name: Rumbl.Supervisor]
    Supervisor.start_link(children, opts)
  end

  # Tell Phoenix to update the endpoint configuration
  # whenever the application is updated.
  def config_change(changed, _new, removed) do
    RumblWeb.Endpoint.config_change(changed, removed)
    :ok
  end
end

rumbl/lib/rumbl/repo.ex
defmodule Rumbl.Repo do
  use Ecto.Repo,
    otp_app: :rumbl,
    adapter: Ecto.Adapters.Postgres
end

rumbl/lib/rumbl_web/controllers/page_controller.ex
defmodule RumblWeb.PageController do
  use RumblWeb, :controller

  def index(conn, _params) do
    render(conn, "index.html")
  end
end

rumbl/lib/rumbl_web/controllers/user_controller.ex
defmodule RumblWeb.UserController do
    use RumblWeb, :controller
    alias Rumbl.Accounts

    def index(conn, _params) do
        user = Accounts.list_users()
        render(conn, "index.html", user: user)
    end

    def show(conn, %{"id" => id}) do
        user = Accounts.get_user(id)
        render(conn, "show.html", user: user)
    end
end

rumbl/lib/rumbl_web/views/error_view.ex
defmodule RumblWeb.ErrorView do
  use RumblWeb, :view

  # If you want to customize a particular status code
  # for a certain format, you may uncomment below.
  # def render("500.html", _assigns) do
  #   "Internal Server Error"
  # end

  # By default, Phoenix returns the status message from
  # the template name. For example, "404.html" becomes
  # "Not Found".
  def template_not_found(template, _assigns) do
    Phoenix.Controller.status_message_from_template(template)
  end
end

rumbl/lib/rumbl_web/views/layout_view.ex
defmodule RumblWeb.LayoutView do
  use RumblWeb, :view
end

rumbl/lib/rumbl_web/views/page_view.ex
defmodule RumblWeb.PageView do
  use RumblWeb, :view
end

rumbl/lib/rumbl_web/views/user_view.ex
defmodule RumblWeb.UserView do
    use RumblWeb, :view
    alias Rumbl.Accounts

    def first_name(%Accounts.User{name: name}) do
        name
        |> String.split(" ")
        |> Enum.at(0)
    end
end 

rumbl/lib/rumbl_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>Rumbl · Phoenix Framework</title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
    <script defer type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </head>
  <body>
    <header>
      <section class="container">
        <nav role="navigation">
          <ul>
            <li><a href="https://hexdocs.pm/phoenix/overview.html">Get Started</a></li>
            <%= if function_exported?(Routes, :live_dashboard_path, 2) do %>
              <li><%= link "LiveDashboard", to: Routes.live_dashboard_path(@conn, :home) %></li>
            <% end %>
          </ul>
        </nav>
        <a href="https://phoenixframework.org/" class="phx-logo">
          <img src="<%= Routes.static_path(@conn, "/images/phoenix.png") %>" alt="Phoenix Framework Logo"/>
        </a>
      </section>
    </header>
    <main role="main" class="container">
      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
      <%= @inner_content %>
    </main>
  </body>
</html>

rumbl/lib/rumbl_web/templates/page/index.html.eex
<section class="phx-hero">
  <h1><%= gettext "Welcome to %{name}!", name: "Rumble.io" %></h1>
  <p>Rumble out loud.</p>
</section>

rumbl/lib/rumbl_web/templates/user/index.html.eex
<h1>Listing Users</h1>
<table>
<%= for user <- @user do%>
<tr>
<td><b><%= render "user.html", user: user %></b></td>
<td><b><%= link "View", to: Routes.user_path(@conn, :show, user.id) %></b></td>
</tr>
<%end%>
</table>

rumbl/lib/rumbl_web/templates/user/show.html.eex
<h1>Showing User</h1>
<b><%= render "user.html", user: @user %> </b>

rumbl/lib/rumbl_web/templates/user/user.html.eex
<strong>
<%= first_name(@user)%>
</strong>
(<%= @user.id %>)